# Generated by Django 3.2.5 on 2021-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
