# Generated by Django 3.2.5 on 2021-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_cafe_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
