# Generated by Django 3.2.5 on 2021-07-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_cafe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='takeout_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
